### ISSUE TITLE
CRUD GET MEMBER JSON&XML Test Error

### ISSUE THREAD

**Issue by abdullaharik** [chrisveness/koa-sample-web-app-api-mysql#4]
Hi,

I get error when I run test. I found that conversion at active user bit to boolean not working.

Am I missing something?
Thanks

**Comment by abdullaharik** [comment]
Models/Member.js

`const castBoolean  = require('../app-api/cast-boolean.js');`

`    static async get(id) {
        const result = await global.db.query('Select * From Member Where MemberId = :id', { id });
        const [ members ] = castBoolean.fromMysql(result);
        const member = members[0]; // .map(Lib.isBuffer);
        return member;
    }`

**Comment by chrisveness** [comment]
Apologies for the delay responding.

I've not been able to see the problem here; to be sure, I've added a couple of [new](https://github.com/chrisveness/koa-sample-web-app-api-mysql/blob/bd951c9857197b56b7892a648b63291f377c423b/test/integration/app-api-tests.js#L113) [tests](https://github.com/chrisveness/koa-sample-web-app-api-mysql/blob/bd951c9857197b56b7892a648b63291f377c423b/test/integration/app-api-tests.js#L127) which exercise this code, and they seem fine.

Could you confirm if this seems ok for you now, or otherwise give further details? Thx.

**Comment by chrisveness** [comment]
Closed for lack of activity
